name: build

on:
  push:
    branches:
      - master
  workflow_dispatch: {}
  repository_dispatch: {}

jobs:
  build:
    steps:
      - uses: actions/checkout@v3
      - name: Fix Git safe directory (resolve dubious ownership)
        run: git config --global --add safe.directory /github/workspace
        with:
          fetch-depth: 0

      - name: Fix Git safe.directory issue
        run: git config --global --add safe.directory /github/workspace

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Setup cache for Bundler
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            docs/Gemfile.lock
            docs/vendor/bundle
          key: ${{ runner.os }}-bundler-${{ hashFiles('docs/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-bundler-